### ISSUE TITLE
api url not working

### ISSUE THREAD

**Issue by thienpow** [scaphold-io/react-native-starter-kit#2]
if i am using your api url it can register...

if using my api url
https://api.scaphold.io/graphql/964bd1f0-793a-4940-b24a-06546e854ca1
it doesn't work.

**Comment by thienpow** [comment]
do i have to add the intergration of Algolia and enable Searchable for user table?

**Comment by vning93** [comment]
You don't need to add any integrations, but what you will need to do is add a type called `HackerNewsItem`. The `User` type is connected to `HackerNewsItem` through a one-to-many relationship called `hackerNewsItems` with a reverse name of `author`.

![Uploading Screen Shot 2016-09-15 at 3.56.10 AM.png…]()

**Comment by vning93** [comment]
You don't need to add any integrations, but what you will need to do is add a type called `HackerNewsItem`. The `User` type is connected to `HackerNewsItem` through a one-to-many relationship called `hackerNewsItems` with a reverse name of `author`.

<img width="1186" alt="screen shot 2016-09-15 at 3 56 10 am" src="https://cloud.githubusercontent.com/assets/6394075/18547555/e29677b8-7af8-11e6-848e-1db2c1416395.png">

Hope this helps!

**Comment by thienpow** [comment]
do i have to add "permission" to the type?  i created the HackerNewsItem type but still fail to register.

**Comment by vning93** [comment]
You do not have to add any permissions. Looks like your API still does not have the HackerNewsItem type for the URL you provided above.

**Comment by thienpow** [comment]
sorry i changed to use 
https://api.scaphold.io/graphql/testabc
<img width="1280" alt="screen shot 2016-09-15 at 7 43 02 pm" src="https://cloud.githubusercontent.com/assets/9796623/18548718/d944f6f6-7b7c-11e6-9b80-685347e906e2.png">

**Comment by thienpow** [comment]
ok looks like i have done something wrong, i should create the hackerNewsItems field at User type instead of creating the author field at HackerNewsItem type... but after recreating the field, tested still cannot

**Comment by vning93** [comment]
What errors are you getting in your console when you debug?

**Comment by thienpow** [comment]
<img width="1280" alt="screen shot 2016-09-15 at 8 09 43 pm" src="https://cloud.githubusercontent.com/assets/9796623/18549347/7d752f4a-7b80-11e6-80b5-2888aa2aa179.png">
no error, just the warning that exist during startup.

**Comment by thienpow** [comment]
<img width="1280" alt="screen shot 2016-09-15 at 8 23 56 pm" src="https://cloud.githubusercontent.com/assets/9796623/18549648/5e553374-7b82-11e6-9fa8-eff3a340602f.png">

this is the schema on apiurl https://api.scaphold.io/graphql/testabc

**Comment by thienpow** [comment]
it should be following what you have there, still not working.

**Comment by vning93** [comment]
I just check out your API using a test app that I have. Can you try again? I think there was an issue in your schema, but I went ahead and fixed it. The schema on the backend must've gotten out of sync somehow.

**Comment by thienpow** [comment]
ya, i can't see the different you have made on the schema... but you have fixed it lol... it works now.

**Comment by thienpow** [comment]
btw Thanks!

i will continue on adding Auth0 later.

**Comment by vning93** [comment]
Great! You probably won't be able to see the difference on your side. It was a mix up in the way it was stored on Scaphold.

**Comment by vning93** [comment]
Feel free to join our Slack channel (https://scapholdslackin.herokuapp.com) and ping me directly if you need more help! My username is @vince in the Slack channel. Cheers!

**Comment by vince** [comment]
@vning93 , I doubt your username is vince because that's my username. Which is why I'm suddenly on this thread.

**Comment by vning93** [comment]
Wow! Hi @vince. I meant my username in the Slack channel that I linked to above. I can't believe you got @vince on Github. That's awesome!
