### ISSUE TITLE
only supporting old release..??

### ISSUE THREAD

**Issue by MeKarina** [scaphold-io/react-native-starter-kit#3]
i'm talking about this..

https://github.com/scaphold-io/react-native-starter-kit/blob/master/package.json#L8-L16

``` js
"dependencies": {
    "babel-preset-react-native": "^1.8.0",
    "babel-relay-plugin": "^0.8.1",
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-native-button": "^1.6.0",
    "react-relay": "^0.8.1",
    "sync-request": "^3.0.1"
 }
```

**Comment by vning93** [comment]
The project should support the latest versions of those dependencies. The `^` in front of the version number means to download the latest package above that version, so if you're running `npm install` from an clean copy, then you should be getting the latest versions of those packages.
