### ISSUE TITLE
Getting these two errors when running "react-native run-ios"

### ISSUE THREAD

**Issue by marioperezpereira** [scaphold-io/react-native-starter-kit#4]
/react-scaphold/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: error: ignoring
      return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
  SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
  ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/react-scaphold/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: error: ignoring
      return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);

**Comment by vning93** [comment]
Thanks for the update. This boilerplate hasn't been updated in a while, and a new one is coming out soon! Stay tuned.

**Comment by M1chaelTran** [comment]
any updates on this?

would be great if there's an [expo ](https://expo.io/)version too.

**Comment by vning93** [comment]
Here's the Exponent version (https://github.com/scaphold-io/exponent-graphql-starter-kit)!
